#!/system/bin/sh

# am start -n com.android.settings/com.android.settings.Settings

mount -o rw,remount /
mount -o rw,remount /system

mkdir /data/media/0/Zacharee1Mods/apks
mkdir /data/media/0/Zacharee1Mods/mod
mkdir /data/media/0/Zacharee1Mods/mod/go

unzip -od /data/media/0/Zacharee1Mods/mod/go/ /data/media/0/Zacharee1Mods/"$1"

cp /data/media/0/Zacharee1Mods/zip /system/bin/zip
chmod 0755 /system/bin/zip

cp /system/priv-app/LGSignBoard/LGSignBoard.apk /data/media/0/Zacharee1Mods/apks/LGSignBoard.apk
cd /data/media/0/Zacharee1Mods/mod/go/
zip -rv /system/priv-app/LGSignBoard/LGSignBoard.apk ./res/layout/*

chmod 0644 /system/priv-app/LGSignBoard/LGSignBoard.apk

rm -rf /data/media/0/Zacharee1Mods/mod/
killall com.lge.signboard