#!/system/bin/sh

# am start -n com.android.settings/com.android.settings.Settings

mount -o rw,remount /
mount -o rw,remount /system

mkdir /data/media/0/Zacharee1Mods/apks
mkdir /data/media/0/Zacharee1Mods/mod
mkdir /data/media/0/Zacharee1Mods/mod/res
mkdir /data/media/0/Zacharee1Mods/mod/res/drawable

unzip -od /data/media/0/Zacharee1Mods/mod/ /data/media/0/Zacharee1Mods/"$1"

cp /data/media/0/Zacharee1Mods/zip /system/bin/zip
chmod 0755 /system/bin/zip

cp -a /data/media/0/Zacharee1Mods/mod/xml/. /data/media/0/Zacharee1Mods/mod/res/drawable/

cp /system/priv-app/LGQuickTools/LGQuickTools.apk /data/media/0/Zacharee1Mods/apks/LGQuickTools.apk
cd /data/media/0/Zacharee1Mods/mod/
zip -rv /system/priv-app/LGQuickTools/LGQuickTools.apk ./res/drawable/*

chmod 0644 /system/priv-app/LGQuickTools/LGQuickTools.apk

rm -rf /data/media/0/Zacharee1Mods/mod/
killall com.lge.signboard
killall com.lge.quicktools