#!/system/bin/sh

# am start -n com.android.settings/com.android.settings.Settings

mount -o rw,remount /
mount -o rw,remount /system

mkdir /data/media/0/Zacharee1Mods/mod
unzip -od /data/media/0/Zacharee1Mods/mod/ /data/media/0/Zacharee1Mods/restoreall.zip

cp /data/media/0/Zacharee1Mods/zip /system/bin/zip
chmod 0755 /system/bin/zip

cd /data/media/0/Zacharee1Mods/mod/SignBoard/
zip -rv /system/priv-app/LGSignBoard/LGSignBoard.apk ./res/layout/*

chmod 0644 /system/priv-app/LGSignBoard/LGSignBoard.apk
rm -rf /data/media/0/Zacharee1Mods/mod/
killall com.lge.quicktools
killall com.lge.signboard